name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish project
      run: dotnet publish --self-contained false
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: my-artifact
        path: bin\Release\net6.0-windows10.0.17763.0\win-x64\publish\
        if-no-files-found: echo "Build failed / Could not find file"
