name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish project as framework-dependent
      run: dotnet publish -c Release --self-contained false
    - name: Rename output file (framework-dependent)
      run: mv D:\a\utilities-cs\utilities-cs\bin\Release\net6.0-windows10.0.17763.0\win-x64\publish\utilities-cs.exe D:\a\utilities-cs\utilities-cs\bin\Release\net6.0-windows10.0.17763.0\win-x64\publish\utilities-cs-framework-dependent.exe
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: framework-dependent
        path: D:\a\utilities-cs\utilities-cs\bin\Release\net6.0-windows10.0.17763.0\win-x64\publish\utilities-cs-framework-dependent.exe
    - name: Publish project as self-contained
      run: dotnet publish -c Release --self-contained true
    - name: Rename output file
      run: mv D:\a\utilities-cs\utilities-cs\bin\Release\net6.0-windows10.0.17763.0\win-x64\publish\utilities-cs.exe D:\a\utilities-cs\utilities-cs\bin\Release\net6.0-windows10.0.17763.0\win-x64\publish\utilities-cs-self-contained.exe
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: self-contained
        path: D:\a\utilities-cs\utilities-cs\bin\Release\net6.0-windows10.0.17763.0\win-x64\publish\utilities-cs-self-contained.exe 
