name: .NET

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: dotnet publish -c Release --self-contained false
    - name: Dewindow binary
      run: |
        cd .\bin\Release\netcoreapp3.1\win-x64\publish
        editbin.exe /subsystem:windows .\utilities-cs.exe
    - name: Archive binary
      uses: actions/checkout@v2
      with:
        name: utilities-cs
        path: .\bin\Release\netcoreapp3.1\win-x64\publish\utilities-cs.exe
        retention-days: 5
        
    
